Updated the workflow to have a failed step

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -8,3 +8,12 @@ jobs:
     steps:
       - name: Say Hello
         run: echo "Hello, world!"
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed step
+        run: |
+          echo "This step will fail"
+          exit 1
+      - name: Say Goodbye
+        run: echo "Goodbye, world!"
